name: Deploy to Local Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          cd C:\Users\Rifat\Desktop\Apex tesing server\test-cicd
          npm install
          
      - name: Build Project
        run: |
          cd C:\Users\Rifat\Desktop\Apex tesing server\test-cicd
          npm run build
          
      - name: Deploy Application
        run: |
          cd C:\Users\Rifat\Desktop\Apex tesing server\test-cicd
          pm2 restart test_cicd
