name: React Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to server
      env:
        SERVER_USER: ${{ secrets.MY_SERVER_USER }}
        SERVER_IP: ${{ secrets.MY_SERVER_IP }}
        SERVER_DIR: ${{ secrets.MY_SERVER_DIR }}
      run: |
        scp -r build/* $SERVER_USER@$SERVER_IP:$SERVER_DIR
        ssh $SERVER_USER@$SERVER_IP "pm2 stop all && pm2 serve $SERVER_DIR 3080 --spa"
