name: React Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Install sshpass
      run: choco install sshpass

    - name: Deploy to server
      env:
        SERVER_USER: ${{ secrets.MY_SERVER_USER }}
        SERVER_IP: ${{ secrets.MY_SERVER_IP }}
        SERVER_DIR: ${{ secrets.MY_SERVER_DIR }}
        SERVER_PASSWORD: ${{ secrets.MY_SERVER_PASSWORD }}
      run: |
        sshpass -p ${env:SERVER_PASSWORD} scp -r build/* ${env:SERVER_USER}@${env:SERVER_IP}:${env:SERVER_DIR}
        sshpass -p ${env:SERVER_PASSWORD} ssh ${env:SERVER_USER}@${env:SERVER_IP} "pm2 stop all && pm2 serve ${env:SERVER_DIR} 3080 --spa"