name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 192.168.20.10
        username: rifat
        password: Apex@123
        port: 22
        script: |
          cd C:\Users\Rifat\Desktop\Apex tesing server\andron
          git pull origin main
          npm install
          npm run build
          pm2 restart Andron
